# Generated by Django 3.1.7 on 2021-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.TextField(blank=True, null=True)),
                ('wpm', models.IntegerField(blank=True, null=True)),
                ('fouten', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('moeilijkheidsgraad', models.TextField(blank=True, null=True)),
                ('taal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Highscore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Woord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('woord', models.TextField(blank=True, null=True)),
                ('taal', models.TextField(blank=True, null=True)),
                ('moeilijkheidsgraad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Woord',
                'managed': False,
            },
        ),
    ]
